export const listOfMoviesGenres = [
  'Acțiune',
  'Acțiune‎',
  'Animație‎',
  'Anime‎',
  'Arte marțiale‎',
  'Artă‎',
  'Avant-garde și experimentale‎',
  'Aventură‎',
  'Basme‎',
  'Biografice',
  'Comedie',
  'Cu lumi pierdute‎',
  'Cu nave spațiale‎',
  'Cu pirați‎',
  'Cu spioni‎',
  'Cu vampiri',
  'Cu zombii',
  'De dragoste',
  'Desene animate',
  'Despre copii‎',
  'Dinozauri‎',
  'Documentare',
  'Dramatice‎',
  'Ecranizări de opere literare',
  'Epocă‎',
  'Erotice',
  'Fantezie‎',
  'Ficțiune‎',
  'Filme epice',
  'Groază‎',
  'Interzise‎',
  'Istorice',
  'Mister',
  'Mumii',
  'Mute',
  'Muzicale‎',
  'Parodii‎',
  'Politice‎',
  'Polițiste‎',
  'Propagandă‎',
  'Religioase‎',
  'Război',
  'Sitcom‎',
  'Sociale‎',
  'Sportive‎',
  'Supraviețuire‎',
  'Thrillere‎',
  'Western‎',
];

export const listOfTVSeries = [
  {
    label: "Dr. Horrible's Sing-Along Blog",
    value: "Dr. Horrible's Sing-Along Blog",
  },
  {
    label: "It's Always Sunny in Philadelphia",
    value: "It's Always Sunny in Philadelphia",
  },
  { label: 'Shadows', value: 'Shadows' },
  { label: "That '70s Show", value: "That '70s Show" },
  { label: "The Handmaid's Tale", value: "The Handmaid's Tale" },
  { label: "Tom Clancy's Jack Ryan", value: "Tom Clancy's Jack Ryan" },
  { label: '11.22.63', value: '11.22.63' },
  { label: '13 Reasons Why', value: '13 Reasons Why' },
  { label: '24: Live Another Day', value: '24: Live Another Day' },
  { label: '30 Rock', value: '30 Rock' },
  { label: 'Adventure Time', value: 'Adventure Time' },
  { label: 'After Life', value: 'After Life' },
  { label: 'Altered Carbon', value: 'Altered Carbon' },
  { label: 'American Crime Story', value: 'American Crime Story' },
  { label: 'American Horror Story', value: 'American Horror Story' },
  { label: 'Anne with an E', value: 'Anne with an E' },
  { label: 'Archer', value: 'Archer' },
  { label: 'Arrested Development', value: 'Arrested Development' },
  { label: 'Arrow', value: 'Arrow' },
  { label: 'Ash vs Evil Dead', value: 'Ash vs Evil Dead' },
  { label: 'Atlanta', value: 'Atlanta' },
  { label: 'Attack on Titan', value: 'Attack on Titan' },
  { label: 'Atypical', value: 'Atypical' },
  { label: 'Avatar: The Last Airbender', value: 'Avatar: The Last Airbender' },
  { label: 'Band of Brothers', value: 'Band of Brothers' },
  { label: 'Banshee', value: 'Banshee' },
  { label: 'Bates Motel', value: 'Bates Motel' },
  {
    label: 'Batman: The Animated Series',
    value: 'Batman: The Animated Series',
  },
  { label: 'Battlestar Galactica', value: 'Battlestar Galactica' },
  {
    label: 'Behzat Ç.: Bir Ankara Polisiyesi',
    value: 'Behzat Ç.: Bir Ankara Polisiyesi',
  },
  { label: 'Berserk', value: 'Berserk' },
  { label: 'Better Call Saul', value: 'Better Call Saul' },
  { label: 'Big Little Lies', value: 'Big Little Lies' },
  { label: 'Billions', value: 'Billions' },
  { label: 'Black Books', value: 'Black Books' },
  { label: 'Black Mirror', value: 'Black Mirror' },
  { label: 'Black Sails', value: 'Black Sails' },
  { label: 'Blackadder Goes Forth', value: 'Blackadder Goes Forth' },
  { label: 'Blackadder II', value: 'Blackadder II' },
  { label: 'Blackadder the Third', value: 'Blackadder the Third' },
  { label: 'Blue Mountain State', value: 'Blue Mountain State' },
  { label: 'BoJack Horseman', value: 'BoJack Horseman' },
  { label: 'Boardwalk Empire', value: 'Boardwalk Empire' },
  { label: 'Bodyguard', value: 'Bodyguard' },
  { label: 'Bosch', value: 'Bosch' },
  { label: 'Boston Legal', value: 'Boston Legal' },
  { label: 'Breaking Bad', value: 'Breaking Bad' },
  { label: 'Broadchurch', value: 'Broadchurch' },
  { label: 'Bron/Broen', value: 'Bron/Broen' },
  { label: 'Brooklyn Nine-Nine', value: 'Brooklyn Nine-Nine' },
  { label: 'Buffy the Vampire Slayer', value: 'Buffy the Vampire Slayer' },
  { label: 'Californication', value: 'Californication' },
  { label: 'Carnivàle', value: 'Carnivàle' },
  { label: 'Castle', value: 'Castle' },
  { label: 'Chernobyl', value: 'Chernobyl' },
  { label: 'Chuck', value: 'Chuck' },
  { label: 'Cobra Kai', value: 'Cobra Kai' },
  {
    label: 'Code Geass: Lelouch of the Rebellion',
    value: 'Code Geass: Lelouch of the Rebellion',
  },
  { label: 'College Romance', value: 'College Romance' },
  { label: 'Community', value: 'Community' },
  { label: 'Coupling', value: 'Coupling' },
  { label: 'Cowboy Bebop', value: 'Cowboy Bebop' },
  { label: 'Criminal Minds', value: 'Criminal Minds' },
  { label: 'Curb Your Enthusiasm', value: 'Curb Your Enthusiasm' },
  { label: 'Daredevil', value: 'Daredevil' },
  { label: 'Dark', value: 'Dark' },
  { label: 'Das Boot', value: 'Das Boot' },
  { label: 'Deadwood', value: 'Deadwood' },
  { label: 'Death Note', value: 'Death Note' },
  { label: 'Dekalog', value: 'Dekalog' },
  { label: 'Dexter', value: 'Dexter' },
  { label: 'Doctor Who', value: 'Doctor Who' },
  { label: 'Downton Abbey', value: 'Downton Abbey' },
  { label: 'Dragon Ball Z', value: 'Dragon Ball Z' },
  { label: 'Dragon Ball', value: 'Dragon Ball' },
  { label: 'Entourage', value: 'Entourage' },
  { label: 'Ezel', value: 'Ezel' },
  { label: 'Family Guy', value: 'Family Guy' },
  { label: 'Fargo', value: 'Fargo' },
  { label: 'Father Ted', value: 'Father Ted' },
  { label: 'Fawlty Towers', value: 'Fawlty Towers' },
  { label: 'Firefly', value: 'Firefly' },
  { label: 'Flames', value: 'Flames' },
  { label: 'Fleabag', value: 'Fleabag' },
  { label: 'Forever', value: 'Forever' },
  { label: 'Freaks and Geeks', value: 'Freaks and Geeks' },
  { label: 'Friday Night Lights', value: 'Friday Night Lights' },
  { label: 'Friends', value: 'Friends' },
  { label: 'Fringe', value: 'Fringe' },
  { label: 'Fullmetal Alchemist', value: 'Fullmetal Alchemist' },
  {
    label: 'Fullmetal Alchemist: Brotherhood',
    value: 'Fullmetal Alchemist: Brotherhood',
  },
  { label: 'Futurama', value: 'Futurama' },
  { label: 'Game of Thrones', value: 'Game of Thrones' },
  { label: 'Generation Kill', value: 'Generation Kill' },
  { label: 'Gilmore Girls', value: 'Gilmore Girls' },
  { label: 'Gomorrah', value: 'Gomorrah' },
  { label: 'Gotham', value: 'Gotham' },
  { label: 'Gravity Falls', value: 'Gravity Falls' },
  { label: 'Hannibal', value: 'Hannibal' },
  { label: 'Hell on Wheels', value: 'Hell on Wheels' },
  { label: 'Homeland', value: 'Homeland' },
  { label: 'House of Cards', value: 'House of Cards' },
  { label: 'House', value: 'House' },
  { label: 'How I Met Your Mother', value: 'How I Met Your Mother' },
  {
    label: 'How to Get Away with Murder',
    value: 'How to Get Away with Murder',
  },
  { label: 'Hunter x Hunter', value: 'Hunter x Hunter' },
  { label: 'Jessica Jones', value: 'Jessica Jones' },
  { label: 'Justice League', value: 'Justice League' },
  { label: 'Justified', value: 'Justified' },
  { label: 'Killing Eve', value: 'Killing Eve' },
  { label: 'Koombiyo', value: 'Koombiyo' },
  { label: 'Kota Factory', value: 'Kota Factory' },
  { label: 'La Casa de Papel', value: 'La Casa de Papel' },
  { label: 'Legion', value: 'Legion' },
  { label: 'Leyla and Mecnun', value: 'Leyla and Mecnun' },
  { label: 'Lie to Me', value: 'Lie to Me' },
  { label: 'Line of Duty', value: 'Line of Duty' },
  { label: 'Lonesome Dove', value: 'Lonesome Dove' },
  { label: 'Lost', value: 'Lost' },
  { label: 'Louie', value: 'Louie' },
  { label: 'Love, Death & Robots', value: 'Love, Death & Robots' },
  { label: 'Lucifer', value: 'Lucifer' },
  { label: 'Luther', value: 'Luther' },
  { label: 'M*A*S*H', value: 'M*A*S*H' },
  { label: 'Mad Men', value: 'Mad Men' },
  { label: 'Malcolm in the Middle', value: 'Malcolm in the Middle' },
  { label: 'Master of None', value: 'Master of None' },
  { label: 'Mindhunter', value: 'Mindhunter' },
  { label: 'Misfits', value: 'Misfits' },
  { label: 'Modern Family', value: 'Modern Family' },
  { label: 'Money Heist', value: 'Money Heist' },
  { label: 'Mr. Robot', value: 'Mr. Robot' },
  { label: 'Narcos', value: 'Narcos' },
  { label: 'Narcos: Mexico', value: 'Narcos: Mexico' },
  { label: 'Naruto', value: 'Naruto' },
  { label: 'Naruto: Shippûden', value: 'Naruto: Shippûden' },
  { label: 'Neon Genesis Evangelion', value: 'Neon Genesis Evangelion' },
  { label: 'North & South', value: 'North & South' },
  { label: 'One Piece: Wan pîsu', value: 'One Piece: Wan pîsu' },
  { label: 'One Punch Man', value: 'One Punch Man' },
  { label: 'Only Fools and Horses', value: 'Only Fools and Horses' },
  { label: 'Orange Is the New Black', value: 'Orange Is the New Black' },
  { label: 'Orphan Black', value: 'Orphan Black' },
  { label: 'Outlander', value: 'Outlander' },
  { label: 'Over the Garden Wall', value: 'Over the Garden Wall' },
  { label: 'Oz', value: 'Oz' },
  { label: 'Ozark', value: 'Ozark' },
  { label: 'Parks and Recreation', value: 'Parks and Recreation' },
  { label: 'Peaky Blinders', value: 'Peaky Blinders' },
  { label: 'Peep Show', value: 'Peep Show' },
  { label: 'Penny Dreadful', value: 'Penny Dreadful' },
  { label: 'Person of Interest', value: 'Person of Interest' },
  { label: 'Persona', value: 'Persona' },
  { label: 'Poirot', value: 'Poirot' },
  { label: 'Pride and Prejudice', value: 'Pride and Prejudice' },
  { label: 'Prison Break', value: 'Prison Break' },
  { label: 'Psych', value: 'Psych' },
  { label: 'Pushing Daisies', value: 'Pushing Daisies' },
  { label: 'Ray Donovan', value: 'Ray Donovan' },
  { label: 'Rick and Morty', value: 'Rick and Morty' },
  { label: 'Rome', value: 'Rome' },
  { label: 'Sacred Games', value: 'Sacred Games' },
  { label: 'Samurai Champloo', value: 'Samurai Champloo' },
  { label: 'Samurai Jack', value: 'Samurai Jack' },
  { label: 'Sarabhai vs Sarabhai', value: 'Sarabhai vs Sarabhai' },
  { label: 'Scrubs', value: 'Scrubs' },
  { label: 'Seinfeld', value: 'Seinfeld' },
  { label: 'Sense8', value: 'Sense8' },
  { label: 'Sex Education', value: 'Sex Education' },
  { label: 'Shameless', value: 'Shameless' },
  { label: 'Sherlock', value: 'Sherlock' },
  { label: 'Silicon Valley', value: 'Silicon Valley' },
  { label: 'Six Feet Under', value: 'Six Feet Under' },
  { label: 'Skam', value: 'Skam' },
  { label: 'Skins', value: 'Skins' },
  { label: 'Sons of Anarchy', value: 'Sons of Anarchy' },
  { label: 'South Park', value: 'South Park' },
  { label: 'Spaced', value: 'Spaced' },
  { label: 'Spartacus', value: 'Spartacus' },
  {
    label: 'Spartacus: Gods of the Arena',
    value: 'Spartacus: Gods of the Arena',
  },
  { label: 'SpongeBob SquarePants', value: 'SpongeBob SquarePants' },
  {
    label: 'Star Trek: The Next Generation',
    value: 'Star Trek: The Next Generation',
  },
  {
    label: 'Star Trek: The Original Series',
    value: 'Star Trek: The Original Series',
  },
  { label: 'Stargate SG-1', value: 'Stargate SG-1' },
  { label: 'Steins;Gate', value: 'Steins;Gate' },
  { label: 'Stranger Things', value: 'Stranger Things' },
  { label: 'Suits', value: 'Suits' },
  { label: 'Supernatural', value: 'Supernatural' },
  { label: 'TVF Pitchers', value: 'TVF Pitchers' },
  { label: 'Taboo', value: 'Taboo' },
  {
    label: 'The Adventures of Sherlock Holmes',
    value: 'The Adventures of Sherlock Holmes',
  },
  { label: 'The Americans', value: 'The Americans' },
  { label: 'The Big Bang Theory', value: 'The Big Bang Theory' },
  { label: 'The Blacklist', value: 'The Blacklist' },
  { label: 'The Boys', value: 'The Boys' },
  { label: 'The Bugs Bunny Show', value: 'The Bugs Bunny Show' },
  { label: 'The Chosen', value: 'The Chosen' },
  { label: 'The Crown', value: 'The Crown' },
  {
    label: 'The End of the F***ing World',
    value: 'The End of the F***ing World',
  },
  { label: 'The Expanse', value: 'The Expanse' },
  { label: 'The Fall', value: 'The Fall' },
  { label: 'The Flash', value: 'The Flash' },
  { label: 'The Good Place', value: 'The Good Place' },
  { label: 'The Good Wife', value: 'The Good Wife' },
  { label: 'The Haunting of Hill House', value: 'The Haunting of Hill House' },
  { label: 'The IT Crowd', value: 'The IT Crowd' },
  { label: 'The Inbetweeners', value: 'The Inbetweeners' },
  { label: 'The Killing', value: 'The Killing' },
  { label: 'The Knick', value: 'The Knick' },
  { label: 'The Last Kingdom', value: 'The Last Kingdom' },
  { label: 'The Leftovers', value: 'The Leftovers' },
  { label: 'The Legend of Korra', value: 'The Legend of Korra' },
  { label: 'The Mandalorian', value: 'The Mandalorian' },
  { label: 'The Marvelous Mrs. Maisel', value: 'The Marvelous Mrs. Maisel' },
  { label: 'The Mentalist', value: 'The Mentalist' },
  { label: 'The Newsroom', value: 'The Newsroom' },
  { label: 'The Night Of', value: 'The Night Of' },
  { label: 'The Office', value: 'The Office' },
  { label: 'The Originals', value: 'The Originals' },
  { label: 'The Pacific', value: 'The Pacific' },
  { label: 'The Punisher', value: 'The Punisher' },
  { label: 'The Shield', value: 'The Shield' },
  { label: 'The Simpsons', value: 'The Simpsons' },
  { label: 'The Sopranos', value: 'The Sopranos' },
  { label: 'The Thick of It', value: 'The Thick of It' },
  { label: 'The Twilight Zone', value: 'The Twilight Zone' },
  { label: 'The Vampire Diaries', value: 'The Vampire Diaries' },
  { label: 'The Walking Dead', value: 'The Walking Dead' },
  { label: 'The West Wing', value: 'The West Wing' },
  { label: 'The Wire', value: 'The Wire' },
  { label: 'The Witcher', value: 'The Witcher' },
  { label: 'The X-Files', value: 'The X-Files' },
  { label: 'This Is Us', value: 'This Is Us' },
  { label: 'Trailer Park Boys', value: 'Trailer Park Boys' },
  { label: 'True Blood', value: 'True Blood' },
  { label: 'True Detective', value: 'True Detective' },
  { label: 'Twin Peaks', value: 'Twin Peaks' },
  { label: 'Two and a Half Men', value: 'Two and a Half Men' },
  { label: 'Unbelievable', value: 'Unbelievable' },
  { label: 'Undercover', value: 'Undercover' },
  { label: 'Utopia', value: 'Utopia' },
  { label: 'Veronica Mars', value: 'Veronica Mars' },
  { label: 'Vikings', value: 'Vikings' },
  { label: 'Westworld', value: 'Westworld' },
  { label: 'When They See Us', value: 'When They See Us' },
  { label: 'White Collar', value: 'White Collar' },
  { label: 'X-Men: The Animated Series', value: 'X-Men: The Animated Series' },
  { label: 'Yeh Meri Family', value: 'Yeh Meri Family' },
  { label: 'Young Justice', value: 'Young Justice' },
];

export const listOfUniversities = [
  { title: 'Universitatea Politehnica din Bucureşti' },
  { title: 'Universitatea Tehnică de Construcţii din Bucureşti' },
  { title: 'Universitatea de Arhitectură și Urbanism Ion Mincu din Bucuresti' },
  {
    title:
      'Universitatea de Stiinte Agronomice și Medicină Veterinară din București',
  },
  { title: 'Universitatea din București' },
  { title: 'Universitatea de Medicina și Farmacie Carol Davila din București' },
  { title: 'Academia de Studii Economice din București' },
  { title: 'Universitatea Naţională de Muzică din Bucureşti' },
  { title: 'Universitatea Naţională de Arte din Bucureşti' },
  {
    title:
      'Universitatea Natională de Artă Teatrală și Cinematografică I.L.Caragiale din București',
  },
  {
    title: 'Universitatea Naţională de Educaţie Fizică și Sport din Bucureşti',
  },
  {
    title:
      'Şcoala Naţională de Studii Politice și Administrative din Bucureşti',
  },
  { title: 'Universitatea 1 Decembrie 1918” din Alba Iulia' },
  { title: 'Universitatea Aurel Vlaicu” din Arad' },
  { title: 'Universitatea Vasile Alecsandri” din Bacău' },
  { title: 'Universitatea Transilvania din Braşov' },
  { title: 'Universitatea Tehnică din Cluj-Napoca' },
  {
    title:
      'Universitatea de Ştiinţe Agricole și Medicină Veterinară din Cluj-Napoca',
  },
  { title: 'Universitatea Babeş-Bolyai din Cluj-Napoca' },
  {
    title:
      'Universitatea de Medicină și Farmacie Iuliu Haţieganu din Cluj-Napoca',
  },
  { title: 'Academia de Muzică Gheorghe Dima din Cluj-Napoca' },
  { title: 'Universitatea de Artă și Design din Cluj-Napoca' },
  { title: 'Universitatea Ovidius din Constanţa' },
  { title: 'Universitatea Maritimă din Constanţa' },
  { title: 'Universitatea din Craiova' },
  { title: 'Universitatea de Medicină și Farmacie din Craiova' },
  { title: 'Universitatea Dunărea de Jos din Galaţi' },
  { title: 'Universitatea Tehnică Gheorghe Asachi din Iaşi' },
  {
    title:
      'Universitatea de Ştiinţe Agricole și Medicină Veterinară Ion Ionescu de La Brad din Iaşi',
  },
  { title: 'Universitatea Alexandru Ioan Cuza din Iaşi' },
  { title: 'Universitatea de Medicină și Farmacie Grigore T. Popa” din Iaşi' },
  { title: 'Universitatea Naţională de Arte George Enescu” din Iaşi' },
  { title: 'Universitatea din Oradea' },
  { title: 'Universitatea din Petroşani' },
  { title: 'Universitatea din Piteşti' },
  { title: 'Universitatea Petrol-Gaze din Ploieşti' },
  { title: 'Universitatea Eftimie Murgu” din Reşiţa' },
  { title: 'Universitatea Lucian Blaga” din Sibiu' },
  { title: 'Universitatea Ştefan Cel Mare” din Suceava' },
  { title: 'Universitatea Valahia din Târgovişte' },
  { title: 'Universitatea Constantin Brâncuşi din Târgu Jiu' },
  {
    title:
      'Universitatea de Medicină, Farmacie, Științe și Tehnologie din Târgu Mureş',
  },
  { title: 'Universitatea de Arte din Târgu Mureş' },
  { title: 'Universitatea Politehnica Timişoara' },
  { title: 'Universitatea de Vest din Timişoara' },
  { title: 'Universitatea de Medicină și Farmacie Victor Babeş din Timişoara' },
  { title: 'Academia Tehnică Militară din Bucureşti' },
  { title: 'Universitatea Naţională de Apărare Carol I din Bucureşti' },
  { title: 'Academia Naţională de Informaţii Mihai Viteazul din Bucureşti' },
  { title: 'Academia de Poliţie Alexandru Ioan Cuza din Bucureşti' },
  { title: 'Academia Forţelor Aeriene Henri Coandă din Braşov' },
  { title: 'Academia Navală Mircea Cel Bătrân din Constanţa' },
  { title: 'Academia Forţelor Terestre Nicolae Bălcescu din Sibiu' },
  { title: 'Universitatea Creştină Dimitrie Cantemir din Bucureşti' },
  { title: 'Universitatea Titu Maiorescu din Bucureşti' },
  { title: 'Universitatea Nicolae Titulescu din Bucureşti' },
  { title: 'Universitatea Româno-Americană din Bucureşti' },
  { title: 'Universitatea Hyperion din Bucureşti' },
  { title: 'Universitatea Spiru Haret din Bucureşti' },
  { title: 'Universitatea Bioterra din Bucureşti' },
  { title: 'Universitatea Ecologică din Bucureşti' },
  {
    title:
      'Universitatea Română de Ştiinţe și Arte Gheorghe Cristea din Bucureşti',
  },
  { title: 'Universitatea Athenaeum din Bucureşti' },
  { title: 'Universitatea Artifex din Bucureşti' },
  { title: 'Institutul Teologic Romano-Catolic din Bucureşti' },
  { title: 'Institutul Teologic Baptist din Bucureşti' },
  { title: 'Institutul Teologic Penticostal din Bucureşti' },
  { title: 'Universitatea Financiar-Bancară din Bucureşti' },
  { title: 'Institutul de Administrare a Afacerilor din Bucureşti' },
  { title: 'Universitatea de Vest Vasile Goldiş din Arad' },
  { title: 'Universitatea George Bacovia din Bacău' },
  { title: 'Universitatea George Bariţiu din Braşov' },
  { title: 'Universitatea Avram Iancu din Cluj-Napoca' },
  { title: 'Universitatea Bogdan Vodă din Cluj-Napoca' },
  { title: 'Institutul Teologic Protestant din Cluj-Napoca' },
  { title: 'Universitatea Sapientia din Cluj-Napoca' },
  { title: 'Universitatea Andrei Şaguna” din Constanţa' },
  { title: 'Universitatea Danubius din Galaţi' },
  { title: 'Universitatea Mihail Kogălniceanu” din Iaşi' },
  { title: 'Universitatea Petre Andrei” din Iaşi' },
  { title: 'Universitatea Apollonia din Iaşi' },
  { title: 'Universitatea Europeană Drăgan” din Lugoj' },
  { title: 'Universitatea Agora din Oradea' },
  { title: 'Universitatea Emanuel din Oradea' },
  { title: 'Universitatea Creştină Partium din Oradea' },
  { title: 'Universitatea Constantin Brâncoveanu din Piteşti' },
  { title: 'Universitatea Româno-germană din Sibiu' },
  { title: 'Universitatea Dimitrie Cantemir din Târgu Mureş' },
  { title: 'Universitatea Mihai Eminescu din Timişoara' },
  { title: 'Universitatea Tibiscus din Timişoara' },
  { title: 'Universitatea Adventus din Cernica' },
  { title: 'Institutul de Studii Europene din Iaşi' },
  { title: 'Institutul Teologic Romano-Catolic Franciscan din Roman' },
  { title: 'Fundaţia Academia Comercială din Satu Mare' },
  { title: 'Universitatea Alma Mater din Sibiu' },
  { title: 'Universitatea Ioan Slavici” din Timişoara' },
  { title: 'Universitatea Tomis din Constanţa' },
  {
    title:
      'Institutul Teologic Creştin După Evanghelie Timotheus din Bucureşti',
  },
  { title: 'Universitatea Europei de Sud-Est - Lumina' },
  { title: 'Școala Normală Superioară București' },
];

export const listOfSports = [
  { label: 'Aerobic', value: 'Aerobic' },
  { label: 'Aeromodelism', value: 'Aeromodelism' },
  { label: 'Aikido', value: 'Aikido' },
  { label: 'Alpinism', value: 'Alpinism' },
  { label: 'Atletism', value: 'Atletism' },
  { label: 'Arte marțiale', value: 'Arte martiale' },
  { label: 'Automobilism', value: 'Automobilism' },
  { label: 'Badminton', value: 'Badminton' },
  { label: 'Balet', value: 'Balet' },
  { label: 'Baschet', value: 'Baschet' },
  { label: 'Biatlon', value: 'Biatlon' },
  { label: 'Biliard', value: 'Biliard' },
  { label: 'Bob', value: 'Bob' },
  { label: 'Box', value: 'Box' },
  { label: 'Bowling', value: 'Bowling' },
  { label: 'Bridge', value: 'Bridge' },
  { label: 'Caiac-canoe', value: 'Caiac-canoe' },
  { label: 'Canotaj', value: 'Canotaj' },
  { label: 'Carting', value: 'Carting' },
  { label: 'Călărie', value: 'Calarie' },
  { label: 'Ciclism', value: 'Ciclism' },
  { label: 'Cricket', value: 'Cricket' },
  { label: 'Culturism', value: 'Culturism' },
  { label: 'Curling', value: 'Curling' },
  { label: 'Dans', value: 'Dans' },
  { label: 'Darts', value: 'Darts' },
  { label: 'Echitație', value: 'Echitatie' },
  { label: 'E-sports', value: 'E-sports' },
  { label: 'Fitness', value: 'Fitness' },
  { label: 'Fotbal', value: 'Fotbal' },
  { label: 'Fotbal american', value: 'Fotbal american' },
  { label: 'Formula 1', value: 'Formula 1' },
  { label: 'Futsal', value: 'Futsal' },
  { label: 'Gimnastică', value: 'Gimnastica' },
  { label: 'Go', value: 'Go' },
  { label: 'Golf', value: 'Golf' },
  { label: 'Haltere', value: 'Haltere' },
  { label: 'Handbal', value: 'Handbal' },
  { label: 'Hochei pe gheață', value: 'Hochei pe gheata' },
  { label: 'Hochei pe iarbă', value: 'Hochei pe iarba' },
  { label: 'Hochei subacvatic', value: 'Hochei subacvatic' },
  { label: 'Înot', value: 'Inot' },
  { label: 'Judo', value: 'Judo' },
  { label: 'Karting', value: 'Karting' },
  { label: 'Karate', value: 'Karate' },
  { label: 'Kick-Box', value: 'Kick-Box' },
  { label: 'Kitesurfing', value: 'Kitesurfing' },
  { label: 'Lupte', value: 'Lupte' },
  { label: 'Motociclism', value: 'Motociclism' },
  { label: 'MMA', value: 'MMA' },
  { label: 'Natație', value: 'Natatie' },
  { label: 'Oină', value: 'Oina' },
  { label: 'Orientare', value: 'Orientare' },
  { label: 'Planorism', value: 'Planorism' },
  { label: 'Parapantism', value: 'Parapantism' },
  { label: 'Parașutism', value: 'Parasutism' },
  { label: 'Patinaj artistic', value: 'Patinaj artistic' },
  { label: 'Patinaj viteză', value: 'Patinaj viteza' },
  { label: 'Paintball', value: 'Paintball' },
  { label: 'Pentatlon', value: 'Pentatlon' },
  { label: 'Pescuit', value: 'Pescuit' },
  { label: 'Petanque', value: 'Petanque' },
  { label: 'Polo', value: 'Polo' },
  { label: 'Raliu', value: 'Raliu' },
  { label: 'Role', value: 'Role' },
  { label: 'Rugby', value: 'Rugby' },
  { label: 'Rugby subacvatic', value: 'Rugby subacvatic' },
  { label: 'Sanie', value: 'Sanie' },
  { label: 'Sărituri cu schiurile', value: 'Sarituri cu schiurile' },
  { label: 'Scrimă', value: 'Scrima' },
  { label: 'Scufundare', value: 'Scufundare' },
  { label: 'Skeleton', value: 'Skeleton' },
  { label: 'Snowboard', value: 'Snowboard' },
  { label: 'Snooker', value: 'Snooker' },
  { label: 'Speologie', value: 'Speologie' },
  { label: 'Streetball', value: 'Streetball' },
  { label: 'Sumo', value: 'Sumo' },
  { label: 'Șah', value: 'Sah' },
  { label: 'Schi', value: 'Schi' },
  { label: 'Surf', value: 'Surf' },
  { label: 'Tae Bo', value: 'Tae Bo' },
  { label: 'Taekwondo', value: 'Taekwondo' },
  { label: 'Tenis de câmp', value: 'Tenis de camp' },
  { label: 'Tenis de masă', value: 'Tenis de masa' },
  { label: 'Tir sportiv', value: 'Tir sportiv' },
  { label: 'Tir cu arcul', value: 'Tir cu arcul' },
  { label: 'Tir dinamic IPSC', value: 'Tir dinamic IPSC' },
  { label: 'Tir subacvatic', value: 'Tir subacvatic' },
  { label: 'Triatlon', value: 'Triatlon' },
  { label: 'Unifight', value: 'Unifight' },
  { label: 'Vânătoare subacvatică', value: 'Vanatoare subacvatica' },
  { label: 'Volei', value: 'Volei' },
  { label: 'Wrestling', value: 'Wrestling' },
  { label: 'Professional Drinking', value: 'Professional Drinking' },
];

export const listOfMusicGenres = [
  { label: 'A cappella', value: 'A cappella' },
  { label: 'Acoustic Blues', value: 'Acoustic Blues' },
  { label: 'African Blues', value: 'African Blues' },
  { label: 'Afro Punk', value: 'Afro Punk' },
  { label: 'Alternative Rap', value: 'Alternative Rap' },
  { label: 'Alternative Rock', value: 'Alternative Rock' },
  { label: 'Alternative', value: 'Alternative' },
  { label: 'Alternativo & Rock Latino', value: 'Alternativo & Rock Latino' },
  { label: 'Ambient', value: 'Ambient' },
  { label: 'Anime', value: 'Anime' },
  { label: 'Art Punk', value: 'Art Punk' },
  { label: 'Asian Underground', value: 'Asian Underground' },
  { label: 'Avant-Garde', value: 'Avant-Garde' },
  { label: 'Bachata', value: 'Bachata' },
  { label: 'Background', value: 'Background' },
  { label: 'Ballet', value: 'Ballet' },
  { label: 'Barbershop', value: 'Barbershop' },
  { label: 'Baroque', value: 'Baroque' },
  { label: 'Bassline', value: 'Bassline' },
  { label: 'Black Metal', value: 'Black Metal' },
  { label: 'Blues Rock', value: 'Blues Rock' },
  { label: 'Blues', value: 'Blues' },
  { label: 'Bolero', value: 'Bolero' },
  { label: 'Bounce', value: 'Bounce' },
  { label: 'Bouncy House', value: 'Bouncy House' },
  { label: 'Bouncy Techno', value: 'Bouncy Techno' },
  { label: 'Breakcore', value: 'Breakcore' },
  { label: 'Cantata', value: 'Cantata' },
  { label: 'Cantopop', value: 'Cantopop' },
  { label: 'Celtic Folk', value: 'Celtic Folk' },
  { label: 'Celtic', value: 'Celtic' },
  { label: 'Chamber Music', value: 'Chamber Music' },
  { label: 'Children’s Music', value: 'Children’s Music' },
  { label: 'Chill Out', value: 'Chill Out' },
  { label: 'Chillstep', value: 'Chillstep' },
  { label: 'Chillwave', value: 'Chillwave' },
  { label: 'Choral', value: 'Choral' },
  { label: 'Christmas', value: 'Christmas' },
  { label: 'Classic Blues', value: 'Classic Blues' },
  { label: 'Classic', value: 'Classic' },
  { label: 'Classical', value: 'Classical' },
  { label: 'Club Dance', value: 'Club Dance' },
  { label: 'Commercial', value: 'Commercial' },
  { label: 'Concerto', value: 'Concerto' },
  { label: 'Contemporary Classical', value: 'Contemporary Classical' },
  { label: 'Contemporary R&B', value: 'Contemporary R&B' },
  { label: 'Country Blues', value: 'Country Blues' },
  { label: 'Country', value: 'Country' },
  { label: 'Death Metal', value: 'Death Metal' },
  { label: 'Deep House', value: 'Deep House' },
  { label: 'Digital Hardcore', value: 'Digital Hardcore' },
  { label: 'Disco', value: 'Disco' },
  { label: 'Disney', value: 'Disney' },
  { label: 'Drinking Songs', value: 'Drinking Songs' },
  { label: 'Drum & Bass', value: 'Drum & Bass' },
  { label: 'Dubstep', value: 'Dubstep' },
  { label: 'Early Music', value: 'Early Music' },
  { label: 'Easter', value: 'Easter' },
  { label: 'Easy Listening', value: 'Easy Listening' },
  { label: 'Electro House', value: 'Electro House' },
  { label: 'Electro', value: 'Electro' },
  { label: 'Electro-swing', value: 'Electro-swing' },
  { label: 'Electroacoustic', value: 'Electroacoustic' },
  { label: 'Electronic Rock', value: 'Electronic Rock' },
  { label: 'Electronic', value: 'Electronic' },
  { label: 'Electroswing', value: 'Electroswing' },
  { label: 'Elevator', value: 'Elevator' },
  { label: 'Environmental', value: 'Environmental' },
  { label: 'Exercise', value: 'Exercise' },
  { label: 'Experimental Rock', value: 'Experimental Rock' },
  { label: 'Fitness & Workout', value: 'Fitness & Workout' },
  { label: 'Flamenco', value: 'Flamenco' },
  { label: 'Folk Punk', value: 'Folk Punk' },
  { label: 'Freestyle House', value: 'Freestyle House' },
  { label: 'Freestyle Rap', value: 'Freestyle Rap' },
  { label: 'Funk', value: 'Funk' },
  { label: 'G-Funk', value: 'G-Funk' },
  { label: 'Gangsta Rap', value: 'Gangsta Rap' },
  { label: 'Golden Age', value: 'Golden Age' },
  { label: 'Goth Rock', value: 'Goth Rock' },
  { label: 'Grime', value: 'Grime' },
  { label: 'Grunge', value: 'Grunge' },
  { label: 'Halloween', value: 'Halloween' },
  { label: 'Happy Hardcore', value: 'Happy Hardcore' },
  { label: 'Hard Rock', value: 'Hard Rock' },
  { label: 'Hardcore Punk', value: 'Hardcore Punk' },
  { label: 'Hardcore Rap', value: 'Hardcore Rap' },
  { label: 'Hardcore', value: 'Hardcore' },
  { label: 'Harmonica Blues', value: 'Harmonica Blues' },
  { label: 'Healing', value: 'Healing' },
  { label: 'Hip Pop', value: 'Hip Pop' },
  { label: 'Hip-Hop', value: 'Hip-Hop' },
  { label: 'Holiday', value: 'Holiday' },
  { label: 'House', value: 'House' },
  { label: 'Hyphy', value: 'Hyphy' },
  { label: 'Indie Rock', value: 'Indie Rock' },
  { label: 'Industrial Hip Hop', value: 'Industrial Hip Hop' },
  { label: 'Instrumental Hip Hop', value: 'Instrumental Hip Hop' },
  { label: 'Instrumental', value: 'Instrumental' },
  { label: 'J-Pop', value: 'J-Pop' },
  { label: 'J-Rock', value: 'J-Rock' },
  { label: 'Japanese Pop', value: 'Japanese Pop' },
  { label: 'Jazz Blues', value: 'Jazz Blues' },
  { label: 'Jazz Rap', value: 'Jazz Rap' },
  { label: 'Jazz', value: 'Jazz' },
  { label: 'Jingles', value: 'Jingles' },
  { label: 'K-Pop', value: 'K-Pop' },
  { label: 'Karaoke', value: 'Karaoke' },
  { label: 'Korean Pop', value: 'Korean Pop' },
  { label: 'Latin Rap', value: 'Latin Rap' },
  { label: 'Latin', value: 'Latin' },
  { label: 'Lo-fi', value: 'Lo-fi' },
  { label: 'Lounge', value: 'Lounge' },
  { label: 'Lullabies', value: 'Lullabies' },
  { label: 'Lyrical Hip Hop', value: 'Lyrical Hip Hop' },
  { label: 'Mambo', value: 'Mambo' },
  { label: 'Mariachi', value: 'Mariachi' },
  { label: 'Medieval', value: 'Medieval' },
  { label: 'Meditation', value: 'Meditation' },
  { label: 'Merengue', value: 'Merengue' },
  { label: 'Metal', value: 'Metal' },
  { label: 'Modern Classical', value: 'Modern Classical' },
  { label: 'Modern Composition', value: 'Modern Composition' },
  { label: 'Movie Soundtrack ', value: 'Movie Soundtrack ' },
  { label: 'Musicals', value: 'Musicals' },
  { label: 'Nature', value: 'Nature' },
  { label: 'New School Hip Hop', value: 'New School Hip Hop' },
  { label: 'Old School Rap', value: 'Old School Rap' },
  { label: 'Opera', value: 'Opera' },
  { label: 'Orchestral', value: 'Orchestral' },
  { label: 'Pop', value: 'Pop' },
  { label: 'Progressive Metal', value: 'Progressive Metal' },
  { label: 'Progressive Rock', value: 'Progressive Rock' },
  { label: 'Progressive', value: 'Progressive' },
  { label: 'Psychedelic', value: 'Psychedelic' },
  { label: 'Psychobilly / Punkabilly', value: 'Psychobilly / Punkabilly' },
  { label: 'Punk', value: 'Punk' },
  { label: 'Quartet', value: 'Quartet' },
  { label: 'R&B/Soul', value: 'R&B/Soul' },
  { label: 'Rap', value: 'Rap' },
  { label: 'Reggae', value: 'Reggae' },
  { label: 'Relaxation', value: 'Relaxation' },
  { label: 'Rock & Roll', value: 'Rock & Roll' },
  { label: 'Rock', value: 'Rock' },
  { label: 'Samba', value: 'Samba' },
  { label: 'Sing-Along', value: 'Sing-Along' },
  { label: 'Soft Rock', value: 'Soft Rock' },
  { label: 'Soul', value: 'Soul' },
  { label: 'Soundtrack', value: 'Soundtrack' },
  { label: 'Steampunk', value: 'Steampunk' },
  { label: 'Stories', value: 'Stories' },
  { label: 'Swing', value: 'Swing' },
  { label: 'Symphonic', value: 'Symphonic' },
  { label: 'Techno', value: 'Techno' },
  { label: 'Trap', value: 'Trap' },
  { label: 'Travel', value: 'Travel' },
  { label: 'Underground Rap', value: 'Underground Rap' },
  { label: 'Vaudeville ', value: 'Vaudeville ' },
  { label: 'Video Game Music', value: 'Video Game Music' },
  { label: 'Vocal', value: 'Vocal' },
  { label: 'Wedding Music', value: 'Wedding Music' },
  { label: 'West Coast Rap', value: 'West Coast Rap' },
];

export const listOfBooksGenres = [
  {
    label: 'Artă, arhitectură și fotografie',
    value: 'Artă, arhitectură și fotografie',
  },
  { label: 'Biografii și memorii', value: 'Biografii și memorii' },
  {
    label: 'Business, economie, finanțe',
    value: 'Business, economie, finanțe',
  },
  { label: 'Dicționare și Enciclopedii', value: 'Dicționare și Enciclopedii' },
  { label: 'Diete și fitness', value: 'Diete și fitness' },
  { label: 'Ficțiune', value: 'Ficțiune' },
  { label: 'Filologie, Filosofie', value: 'Filologie, Filosofie' },
  { label: 'Gastronomie', value: 'Gastronomie' },
  {
    label: 'Ghiduri de călătorie, hărți',
    value: 'Ghiduri de călătorie, hărți',
  },
  { label: 'Hobby, timp liber', value: 'Hobby, timp liber' },
  { label: 'Istorie', value: 'Istorie' },
  { label: 'Limbi străine', value: 'Limbi străine' },
  { label: 'Parenting și familie', value: 'Parenting și familie' },
  { label: 'Psihologie, Pedagogie', value: 'Psihologie, Pedagogie' },
  { label: 'Religie', value: 'Religie' },
  { label: 'Self Help', value: 'Self Help' },
  {
    label: 'Sociologie, științe politice',
    value: 'Sociologie, științe politice',
  },
  { label: 'Spiritualitate, ezoterism', value: 'Spiritualitate, ezoterism' },
  { label: 'Sțiinte', value: 'Sțiinte' },
];

export const listOfHobbies = [
  { label: 'Acrobaţie', value: 'Acrobatie' },
  { label: 'Actorie', value: 'Actorie' },
  { label: 'Airsoft', value: 'Airsoft' },
  { label: 'Alergare', value: 'Alergare' },
  { label: 'Alpinism', value: 'Alpinism' },
  { label: 'Amestecare de băuturi', value: 'Amestecare de bauturi' },
  { label: 'Animaţie', value: 'Animatie' },
  { label: 'Antichități', value: 'Antichitati' },
  { label: 'Antrenamente cu greutăți', value: 'Antrenamente cu greutati' },
  { label: 'Apicultură', value: 'Apicultura' },
  { label: 'Aranjamente florale', value: 'Aranjamente florale' },
  { label: 'Arte digitale', value: 'Arte digitale' },
  { label: 'Artizanat cu flori presate', value: 'Artizanat cu flori presate' },
  { label: 'Artizanat din piele', value: 'Artizanat din piele' },
  { label: 'Artă cu nisip', value: 'Arta cu nisip' },
  { label: 'Aruncarea cuțitului', value: 'Aruncarea cutitului' },
  { label: 'Aruncarea toporului', value: 'Aruncarea toporului' },
  { label: 'Ascultat de muzică', value: 'Ascultat de muzica' },
  { label: 'Ascultat de podcast-uri', value: 'Ascultat de podcast-uri' },
  { label: 'Astronomie', value: 'Astronomie' },
  { label: 'BMX', value: 'BMX' },
  { label: 'Backpacking', value: 'Backpacking' },
  { label: 'Badminton', value: 'Badminton' },
  { label: 'Biliard', value: 'Biliard' },
  { label: 'Blogging', value: 'Blogging' },
  { label: 'Broderie', value: 'Broderie' },
  { label: 'Cabaret', value: 'Cabaret' },
  { label: 'Caligrafie', value: 'Caligrafie' },
  { label: 'Ceramică', value: 'Ceramica' },
  { label: 'Ciclism montan', value: 'Ciclism montan' },
  { label: 'Citit', value: 'Citit' },
  { label: 'Colectatare de insecte', value: 'Colectatare de insecte' },
  { label: 'Colectare de minerale', value: 'Colectare de minerale' },
  { label: 'Colectare de pietre', value: 'Colectare de pietre' },
  { label: 'Colecționare de artă', value: 'Colectionare de arta' },
  { label: 'Colecționare de cărți', value: 'Colectionare de carti' },
  {
    label: 'Colecționare de jocuri video',
    value: 'Colectionare de jocuri video',
  },
  { label: 'Colecționare de monede', value: 'Colectionare de monede' },
  { label: 'Colecționare de timbre', value: 'Colectionare de timbre' },
  { label: 'Condus', value: 'Condus' },
  {
    label: 'Confecționare de încălțăminte',
    value: 'Confectionare de încaltaminte',
  },
  { label: 'Confecționare de lumânări', value: 'Confectionare de lumanari' },
  { label: 'Cosplaying', value: 'Cosplaying' },
  { label: 'Creșterea florilor', value: 'Cresterea florilor' },
  { label: 'Criptografie', value: 'Criptografie' },
  { label: 'Croșetare', value: 'Crosetare' },
  {
    label: 'Colecționare de benzi desenate',
    value: 'Colectionare de benzi desenate',
  },
  { label: 'Culturism', value: 'Culturism' },
  { label: 'Cumpărături', value: 'Cumparaturi' },
  { label: 'Curse auto', value: 'Curse auto' },
  { label: 'Curse de karting', value: 'Curse de karting' },
  { label: 'Cântat', value: 'Cantat' },
  {
    label: 'Cântat la instrumente muzicale',
    value: 'Cantat la instrumente muzicale',
  },
  { label: 'Călărie', value: 'Calarie' },
  { label: 'Dans', value: 'Dans' },
  { label: 'Darts', value: 'Darts' },
  { label: 'Design grafic', value: 'Design grafic' },
  { label: 'Design vestimentar', value: 'Design vestimentar' },
  { label: 'Detectarea metalelor', value: 'Detectarea metalelor' },
  { label: 'Dezvoltare de jocuri video', value: 'Dezvoltare de jocuri video' },
  { label: 'Drumeții', value: 'Drumetii' },
  { label: 'Editare video', value: 'Editare video' },
  { label: 'Electronică', value: 'Electronica' },
  { label: 'Explorare urbană', value: 'Explorare urbana' },
  { label: 'Fierărie', value: 'Fierarie' },
  { label: 'Fotografie', value: 'Fotografie' },
  { label: 'Gaming', value: 'Gaming' },
  { label: 'Graffiti', value: 'Graffiti' },
  { label: 'Grădinărit', value: 'Gradinarit' },
  { label: 'Gătit', value: 'Gatit' },
  { label: 'Hacking', value: 'Hacking' },
  { label: 'Investiții', value: 'Investitii' },
  { label: 'Jocuri de cărți', value: 'Jocuri de carti' },
  { label: 'Jocuri de masă', value: 'Jocuri de masa' },
  { label: 'Jonglerie', value: 'Jonglerie' },
  { label: 'Karaoke', value: 'Karaoke' },
  { label: 'Kendama', value: 'Kendama' },
  { label: 'Lego', value: 'Lego' },
  { label: 'Machiaj', value: 'Machiaj' },
  { label: 'Magie', value: 'Magie' },
  { label: 'Mahjong', value: 'Mahjong' },
  { label: 'Manichiură', value: 'Manichiura' },
  { label: 'Mecanică', value: 'Mecanica' },
  { label: 'Meditaţie', value: 'Meditatie' },
  { label: 'Mersul pe jos', value: 'Mersul pe jos' },
  { label: 'Meteorologie', value: 'Meteorologie' },
  { label: 'Microscopie', value: 'Microscopie' },
  { label: 'Modă', value: 'Moda' },
  { label: 'Origami', value: 'Origami' },
  { label: 'Paintball', value: 'Paintball' },
  { label: 'Parkour', value: 'Parkour' },
  { label: 'Patinaj cu role', value: 'Patinaj cu role' },
  { label: 'Pescuit', value: 'Pescuit' },
  { label: 'Pictură', value: 'Pictura' },
  { label: 'Pocker', value: 'Pocker' },
  { label: 'Prelucrarea lemnului', value: 'Prelucrarea lemnului' },
  { label: 'Prelucrarea metalelor', value: 'Prelucrarea metalelor' },
  { label: 'Privit la televizor', value: 'Privit la televizor' },
  { label: 'Programare', value: 'Programare' },
  { label: 'Puzzle-uri', value: 'Puzzle-uri' },
  { label: 'Rebus', value: 'Rebus' },
  { label: 'Rezolvare de cub Rubik', value: 'Rezolvare de cub Rubik' },
  { label: 'Scris', value: 'Scris' },
  { label: 'Scufundări', value: 'Scufundari' },
  { label: 'Sculptat', value: 'Sculptat' },
  { label: 'Shogi', value: 'Shogi' },
  { label: 'Social media', value: 'Social media' },
  { label: 'Sporturi aeriene', value: 'Sporturi aeriene' },
  { label: 'Stand-up comedy', value: 'Stand-up comedy' },
  { label: 'Tai chi', value: 'Tai chi' },
  { label: 'Taxidermie', value: 'Taxidermie' },
  { label: 'Tir cu arcul', value: 'Tir cu arcul' },
  { label: 'Tricotare', value: 'Tricotare' },
  { label: 'Vizionare de filme', value: 'Vizionare de filme' },
  { label: 'Volei pe plajă', value: 'Volei pe plaja' },
  { label: 'Voluntariat', value: 'Voluntariat' },
  { label: 'Vânătoare', value: 'Vanatoare' },
  { label: 'Vânătoarea de fantome', value: 'Vanatoarea de fantome' },
  { label: 'Yoga', value: 'Yoga' },
  { label: 'Învățare de limbi străine', value: 'Invatare de limbi straine' },
  { label: 'Șah', value: 'Sah' },
];
